#!/bin/bash

#current date and time in custom format
current_date_time=$(date +"%Y-%m-%d/%H:%M:%S")
username=$(whoami)  # Get the username of the current user
osinfo=$([ -f /etc/os-release ] && . /etc/os-release && echo "$NAME $VERSION" || lsb_release -sd || echo "Cannot determine the operating system.")  # Get OS information
system_uptime=$(uptime -p)  # Get system uptime

# display the formatted date and time
echo "System Report generated by : $username $current_date_time"
echo

echo -e "System Information\n------------------"
# show me the hostname
hostname=$(hostname)

# show the hostname and OS information
echo "HOSTNAME: $hostname"
echo "OS: $osinfo"
echo "Uptime: $system_uptime"
echo

echo -e "Hardware Information\n-------------------"
# get CPU info
cpu_info=$(lscpu | grep 'Model name' | cut -d ':' -f 2- | xargs)
echo "cpu: $cpu_info"

# detect CPU speed
cpu_speed=$(lscpu | grep "CPU MHz" | awk '{print $3}')
echo "Speed: $cpu_speed MHz"

# grab RAM size
ram_size=$(free -h | awk '/^Mem/ {print $2}')
echo "Ram: $ram_size"

# show disk info
disks_info=$(lsblk -d -o NAME,MODEL,SIZE --bytes --nodeps | tail -n +2)
echo -e "Disk(s):\n$disks_info"

# get video card info
video_info=$(lspci | grep -i 'VGA\|3D' | awk -F ': ' '{print $2}')
echo " Video: $video_info"
echo

echo -e "Network Information\n------------------"
# detect FQDN
fqdn=$(hostname)
echo "FQDN: $fqdn"

# get host IP addr
echo "Host Address: $(hostname -I)"

# get gateway IP addr
gateway_ip=$(ip route | awk '/default/ {print $3}')
echo "Gateway IP: $gateway_ip"

# get DNS server addr
dns_servers=$(awk '/nameserver/ {print $2}' /etc/resolv.conf)
echo "DNS Server: $dns_servers"
echo

echo -e "Interface Information\n---------------------"
# interface names
echo "Interface Name: $(ip link show | awk -F: '$1 ~ /^[0-9]+$/ {print $2}' | tr -d ' ')"

#IP addresses for interfaces
ip_address=$(ip -o -4 addr show scope global | awk '{print $4}')
echo "IP Address: $ip_address"
echo

echo -e "System Status\n-------------------"
#logged in users
logged_in_users=$(who | awk '{print $1}' | tr '\n' ',' | sed 's/,$//')
echo "Users Logged In: $logged_in_users"

# disk space info
echo "Disk Space:"
sudo df -h | awk '{printf "%-20s %-s\n", $6, $4}'

# get process count
echo "Process Count: $(ps aux | wc -l)"

# get load averages
load_averages=$(uptime | awk -F'load average: ' '{print $2}')
echo "Load Averages: $load_averages"

# get memory allocation info
memory_info=$(free -h | awk 'NR==2 {print "Total: " $2, "Used: " $3, "Free: " $4}')
echo "Memory Allocation: $memory_info"

#listening network ports
echo "Listening Network Ports:"
sudo lsof -i -P -n | grep LISTEN

# firewall rules
echo "UFW Rules:"
sudo ufw status | sed 2d
